### PR TITLE
Make query & queryAll throw if no this.el

### LINKED ISSUE #91: Handle view.query() being invoked when view.el is undefined
Currently, if `view.el` is undefined, a call to `view.query()` will fail with a `Uncaught TypeError: Illegal invocation` inside the `matches-selector` package. It would be nicer to have a check in the query method that handles this condition.

```javascript
query: function (selector) {
        if (!selector) return this.el;
        if (typeof selector === 'string') {
            if (matches(this.el, selector)) return this.el;  // this causes TypeError when this.el is undefined
            return this.el.querySelector(selector) || undefined;
        }
        return selector;
    }
```

You have a guard for this condition in the `queryAll` method, just not in the `query` method.
```javascript
queryAll: function (selector) {
        var res = [];
        if (!this.el) return res;  // guards against condition where this.el === undefined
        if (selector === '') return [this.el];
        if (matches(this.el, selector)) res.push(this.el);
        return res.concat(Array.prototype.slice.call(this.el.querySelectorAll(selector)));
    },
```

### PR DESCRIPTION
**Pull request by pgilad**
- Fixes #91

### CODE REVIEW

**Comment by tragiclifestories** [comment]
Would be good to have a simple test case for this.

**Comment by pgilad** [comment]
@tragiclifestories Rebased and added tests for throwing / not throwing

**Comment by kamilogorek** [comment]
Looks fine.

**Comment by cdaringe** [comment]
+1

**Comment by pgilad** [comment]
Can someone merge this?

**Comment by lukekarrys** [comment]
@pgilad Can you bring this up to date with the latest master? It looks like it has conflicts with some of the stuff that just merged? Then we can merged it.

**Comment by pgilad** [comment]
Done

**Pull request merged**
