### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dhritzkiv**
`ampersand-state`, `ampersand-version`, `ampersand-dom-bindings`, `component-classes`, and `domify`

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1

**Comment by wraithgar** [comment]
It turn out we were using a lodash 2.x module in a few of these, we've since made sure to be using lodash.assign so we were properly in 3.x land.  This is probably worth a revisit to get on the absolute latest so we're sure we're in the clear of conflicts.

**Comment by wraithgar** [comment]
Ok newer PR made that builds off of this.

**Comment by dhritzkiv** [comment]
Great!

**Comment by wraithgar** [comment]
shipped as `v7.2.2`

**Pull request merged**
