### PR TITLE
implementing shorthand syntax for subviews. Fixes #43

### LINKED ISSUE #43: Shorthands for subview declaration
Wouldn't it be great if you could do like this when you declared subviews?

```javascript
    subviews: {
        status: {
            container: '[role=status]',
            constructor: StatusView,
            // No model is set so it defaults to its parent model.
        }
    }
```

```javascript
    subviews: {
        user: {
            container: '[role=user]',
            constructor: UserView,
            model: 'model.user' // Will set model to model.user and automatically wait for it.
        },
    }
```

```javascript
    subviews: {
        todos: {
            container: '[role=todos]',
            constructor: TodoView,
            collection: 'model.todos' // Will set collection to model.todos and automatically wait for it.
        }
    }
```

Right now it looks like this in my code. 

```javascript
    subviews: {
       status: {
            container: '[role=status]',
            waitFor: 'model',
            prepareView: function (el) {
                return new StatusView({
                    el: el,
                    model: this.model
                });
            }
        },
        user: {
            container: '[role=user]',
            waitFor: 'model.user',
            prepareView: function (el) {
                return new UserView({
                    el: el,
                    model: this.model.user
                });
            }
        },
        todos: {
            container: '[role=todos]',
            constructor: TodoView,
            waitFor: 'model.todos',
            prepareView: function (el) {
                return new TodoView({
                    el: el,
                    collection: this.model.todos
                });
            }
        }
    }
```

I can implement it, but first I would like to know if I missing something and if it is a good idea. What are the downsides to auto assigning parent model as model? What are the downsides to the two new shorthands?

### PR DESCRIPTION
**Pull request by HenrikJoreteg**

### CODE REVIEW

**Comment by gonsfx** [comment]
I completely agree with @ngryman and was wondering why this wasn't possible in the first place.

:+1: from me!

**Comment by ferdinandsalis** [comment]
I expected it work this way. :+1: from me too.

**Comment by pgilad** [comment]
I think allowing the user to pass arbitrary properties to the constructor of the subview is great.

I disagree with passing `this.model` and `this.collection` by default. This might cause **garbage collection** problem when parent view de-references the model or collection and child will still hold their reference (even though it might not be using them).

This is why I think that if by default user wants to pass along `model` or `collection` he should override the `prepareView` himself.

**Comment by cdaringe** [comment]
if someone wants to pick this one up and run with it, please do! tagging as such

**Pull request closed without merging**
