### PR TITLE
Attempted fix for issue #137

### PR DESCRIPTION
**Pull request by bryanspears**
Expands the waitFor check to allow for numeric `0` and boolean `false`

### CODE REVIEW

**Comment by pgilad** [comment]
Hey - please see my comment, and can you also add a test case for this?

**Comment by bryanspears** [comment]
I removed my own version of this due to collections. I haven't had a chance to revisit and see if there's a succinct way to waitFor models and collections accurately. A truthy check doesn't consistently work on collections as they instantiate empty collections when added as a collection to a model.

I hope to revisit this PR soon and come up with a solution that hopefully works consistently and makes sense at a glance what's happening. Waiting for 'model.<collection name>.length' doesn't make sense to me at all when waiting on a restful collection to sync. And doing it by hand with even listeners works, but I think it can be done better with a more robust waitFor.

**Comment by pgilad** [comment]
A more robust solution will use `result` instead of `getPath`, and thus allowing you to set a custom callback which you will trigger when you want to.
This allows for `listenToOnce` events which you can use to hook into `sync` events for example.

**Comment by bryanspears** [comment]
I'll pursue that train of thought next opportunity I have. Thanks for the input!

**Comment by cdaringe** [comment]
closing pending further activity

**Pull request closed without merging**
