### PR TITLE
merge parent definitions onto the child when extending

### LINKED ISSUE #39: Hashes (events, bindings, subviews) could be merged with superclass definitions
Similar to what is done with session/props/derived on ampersand-state.

I was working on a module recently and had to override View.extend to get this behavior. But in my opinion, I could see this being beneficial to a lot of apps. Thoughts?

### PR DESCRIPTION
**Pull request by lukekarrys**
Added this behavior for events/bindings/subviews hashes

Closes #39

### CODE REVIEW

**Comment by gonsfx** [comment]
I would love to see this merged to `master`.
Any progress on this?

**Comment by pgilad** [comment]
I would vote against adding a flag for property merges. That would cause debugging hell down the line.
If users wish to merge properties, provide a mixin module that will take 2 hashes (nested as well for props whatsoever) and return a mixed hash:

```js
var unit1 = View.extend({
    events: {
        'click [role="reset"]': 'resetSomething'
    }
});

var unit2 = View.extend({
    events: {
        'blur [role="reset"]': 'doSomething'
    }
});

// use lodash.assign or lodash.merge (for recursive) or any custom merge module
unit2.prototype.events = _.assign({}, unit1.events, unit2.events);
```

This way users can choose whether to merge properties, and also (as important) in what order.

[Favor composition over inheritance](http://en.wikipedia.org/wiki/Composition_over_inheritance)

**Comment by HenrikJoreteg** [comment]
Given the mediocre enthusiasm about this and the potential confusion it could cause I'm going to close this. I'm with @pgilad that this could be quite confusing. 

I don't see a strong enough case for this being worth the extra complexity.

**Comment by gonsfx** [comment]
How can merging the parent definitions of `events`, `bindings` and `subviews` hashes onto the child when extending be considered confusing while merging the parent definitions of `dataTypes`, `props`, `session`, `derived`, `collections` and `children` (all inherited from `ampersand-state`) is not?

:confused:

**Comment by pgilad** [comment]
@gonsfx To be totally honest, I feel that automatic property merging is usually a mistake. (Yes also https://github.com/AmpersandJS/ampersand-state/blob/master/ampersand-state.js#L745-L750 is a mistake).
Property merging should be done manually (recursively or not, with desired assignment order) by the client of the package.
Thus I also feel the custom `extend` method implemented by `ampersand-state` and it's difference from other `extend` methods by other ampersand packages is an inconsistency.

As you said - either always be merging properties (or allow user to choose to selectively do so), or always let the consumer merge properties.

I personally would much rather do this:
`unit2.prototype.events = _.assign({}, unit1.events, unit2.events);`

Than this:
`unit2.extend({ ..., mergeProperties: ['events', 'bindings'], mergeRecursive: false, mergeOrder: 'parent' ...})`

This puts too much stress on the the library itself to provide for everything you need.

*Notice how in the `assign` variation, all the options are already handled by me.

**Comment by gonsfx** [comment]
Exactly my point. I don't like merging some and not merging others. I'm fine with merging everything myself.

**Comment by pgilad** [comment]
Yeah, in this case, **imperative** merging of props is preferred.

**Comment by latentflip** [comment]
> How can merging the parent definitions of events, bindings and subviews hashes
onto the child when extending be considered confusing while merging the
parent definitions of dataTypes, props, session, derived, collections and
children (all inherited from ampersand-state) is not?

Not saying it's perfect, but automatically merging props is a lot easier,
and arguably less confusing, than merging events/bindings.

Props defined in a "subclass" or a mixin either simply create new property
definitions, or replace existing ones.

You can't make the same assumptions for merging, e.g. bindings. Did you
want to replace an existing binding, or add to it? Same with events.

So yes, I do think that automatically merging props is less confusing than
merging the others. Now, we as you're suggesting, we could make the case
that _nothing_ should be merged automatically on inheritance, and we could
provide utility functions for doing that yourself instead. But that'd have
pretty significant effects on the way both inheritance and mixins currently
work, and I'd say it's a tossup as to whether that change would be an
overall benefit or not.

**Comment by pgilad** [comment]
@latentflip Would that potentially allow the usage of ES6 `class` with `ampersand`?

(BTW I hate that feature of es6 and think it should be killed, because inheritance...)

**Comment by latentflip** [comment]
It probably wouldn't significantly change the story of trying to create
ampersand models with es6 classes no. The issues are outlined
in: AmpersandJS/ampersand-state.

As someone who's now doing a lot more es6 stuff, I'm still fairly sure that
for now the drawbacks of trying to make `class MyState extends
AmpersandState {}` significantly outweigh the benefits.

**Comment by edorsey** [comment]
Maybe it would be best to release this as a mixin? Then people who are writing re-usable components can include it manually.

**Comment by HenrikJoreteg** [comment]
I agree with @latentflip here. Given that `props` was the main purpose of state, people were confused when they were not being automatically merged. For a while we didn't have an `extend` we simply had a `define` method. 

But also, to those wanting to manually extend everything, there's nothing stopping you from writing your code that way now, right? Just don't use inheritance in that way instead put your props in a module and use assign or whatever to merge props before you define your model/view or whatever right?

Pattern-wise i've been doing a lot more composition than inheritance myself. /me shrugs

**Pull request closed without merging**
