### PR TITLE
return `this` from cacheElements

### PR DESCRIPTION
**Pull request by nathanstitt**
By doing so, it will allow easier chaining
of additional method calls after render()

### CODE REVIEW

**Comment by wraithgar** [comment]
Pinging @AmpersandJS/core-team let's use this or lose this.

**Comment by HenrikJoreteg** [comment]
@wraithgar I'm fine with returning `this` but I don't want to change the examples/docs to show that you should do `return this.cacheElements`

**Comment by lukekarrys** [comment]
+1 on @HenrikJoreteg's points

**Comment by wraithgar** [comment]
Merged w/o readme updates.

**Comment by wraithgar** [comment]
published as `v7.3.0`

**Pull request merged**
