### PR TITLE
Bump ampersand-state to ^5.0.1

### PR DESCRIPTION
**Pull request by janpaul123**
So we can benefit from https://github.com/AmpersandJS/ampersand-state/pull/235 in ampersand-view.

### CODE REVIEW

**Comment by janpaul123** [comment]
Could you have a look at this @cdaringe @lukekarrys?

**Comment by cdaringe** [comment]
sorry for missing it earlier, @janpaul123.  looks fine to me :) +1

**Comment by pgilad** [comment]
👍

**Comment by janpaul123** [comment]
Great, thank you!

**Comment by cdaringe** [comment]
`v10.0.0` published

**Pull request merged**
