### PR TITLE
Do not throw if template root has comment node as a sibling

### PR DESCRIPTION
**Pull request by kamilogorek**
Quick solution idea for https://github.com/AmpersandJS/ampersand-view/issues/88

### CODE REVIEW

**Comment by cdaringe** [comment]
let's make a decision here and close this up! code looks good (+1). @mikehedman has a valid point--perhaps not so minimalist. he's lookin' to help keep @lukekarrys filesize report numbers down :smile:

**Comment by lukekarrys** [comment]
I'd vote for a note in the comments and maybe updating the error message to be `Views can only have one root element, including comment nodes.`

**Comment by HenrikJoreteg** [comment]
I'm with @lukekarrys on this. Let's improve the error thrown as per his suggestion.

**Comment by kamilogorek** [comment]
Updated.

**Comment by HenrikJoreteg** [comment]
@kamilogorek sorry, I don't think I was clear enough. What I'm thinking is we *just* change the error but remove the other code changes. As long as people realize what the error is I think it's fine to not support having a comment at the root. Most template languages have some syntax to allow comments that don't end up in the compiled source anyway.

**Comment by kamilogorek** [comment]
@HenrikJoreteg ok, sounds fair enough. Reversed and updated.

**Comment by HenrikJoreteg** [comment]
+1 :shipit:

**Comment by wraithgar** [comment]
released as `v7.4.2`

**Pull request merged**
